model_list:
  - model_name: flora-brain-hq
    litellm_params:
      model: ollama/qwen3.5:latest
      api_base: "http://192.60.1.110:11434"
    model_info:
      id: "pc-gpu"
      priority: 1

  - model_name: flora-brain-hq-nas
    litellm_params:
      model: ollama/llama3.2:1b
      api_base: "http://192.60.1.114:11434"
    model_info:
      id: "nas-cpu"
      priority: 10

router_settings:
  routing_strategy: "latency-based-routing"
  enable_pre_call_checks: true
